import Head from 'next/head'
import { useReducer } from 'react'
import { Button } from '../components/Button'
import { types } from '../context/types'
import { ValueContext } from '../context/valuecontext'
import { valueReducer } from '../context/valueReducer'
import { Piano } from '../components/Piano'
import { ShowResultScreen } from '../components/ShowResultScreen'



import styles from '../styles/Piano.module.css'

export default function Home() {

  const initialState =
  {
    note: '',
    noteAgain: false


  }

  const [state, dispatch] = useReducer(valueReducer, initialState);

  const handleGlobal = (value) => {
    dispatch({
      type: types.value,
      name: value.name,
      payload: value.payload
    })
  }


  return (
    <ValueContext.Provider value={
      {
        ...state,
        handleGlobal
      }
    }>
      <div className={styles.container}>
        <Head>
          <title>Piano</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

          <Piano />
          <ShowResultScreen />


        </main>
      </div>
    </ValueContext.Provider>
  )
}
